### ISSUE TITLE
Access to the parent Map in the ObjectSerializer

### ISSUE THREAD

**Issue by Silthus** [OkaeriPoland/okaeri-configs#20]
How can I access the key of a `Map<String, Object>` when serializing a custom object?

I have a `Channel` object where I want to map the key of the map to the identifier of the channel. How can I do this?

```java
    @Override
    public boolean supports(final @NonNull Class<? super Channel> type) {
        return Channel.class.isAssignableFrom(type);
    }

    @Override
    public void serialize(final @NonNull Channel object, final @NonNull SerializationData data) {
        data.add("id", object.uuid());
        data.add("identifier", object.identifier()); // <--- set the identifier as the Map.key instead
        data.add("name", object.displayName());
        data.add("format", Objects.requireNonNullElse(object.format(), Channel.DEFAULT_CHANNEL_MESSAGE_FORMAT).getOrNull(Format.MINI_MESSAGE_TEMPLATE));

        for (final Setting<?> setting : object.settings().settings()) {
            data.add(setting.key().asString(), object.getOrNull(setting));
        }
    }

    @Override
    public Channel deserialize(final @NonNull DeserializationData data, final @NonNull GenericsDeclaration generics) {
        final Channel.Builder builder = Channel.channel();

        if (data.containsKey("id"))
            builder.uuid(data.get("id", UUID.class));
        if (data.containsKey("identifier")) // <--- this should come from the Map.key
            builder.identifier(data.get("identifier", String.class));
        if (data.containsKey("name"))
            builder.displayName(data.get("name", Component.class));
        if (data.containsKey("format"))
            builder.format(Format.miniMessageFormat(data.get("format", String.class)));

        for (final Setting<?> setting : Channel.SETTINGS) {
            addSetting(data, builder, setting.key().asString().replace(SChat.NAMESPACE + ":", ""), setting);
        }

        return builder.build();
    }

    private <V> void addSetting(final DeserializationData data, final Channel.Builder builder, final String key, final Setting<V> setting) {
        if (data.containsKey(key))
            builder.setting(setting, data.get(key, setting.type()));
    }
```

**Comment by PinkLolicorn** [comment]
Could you please provide example OkaeriConfig where such elements are used and current + expected result file?

**Comment by Silthus** [comment]
> Could you please provide example OkaeriConfig where such elements are used and current + expected result file?

Wow that was a quick reply :)
Sure!

This is the part where I want to use the Map. If it doesn't work I would fall back to a `List<Channel>`.

```java
    @Comment("Configure your channels here.")
    private Map<String, Channel> channels = new HashMap<>(Map.of(
        "global", Channel.channel()
            .identifier("global")
            .displayName(text("Global"))
            .setting(Channel.PRIVATE, false)
            .setting(Channel.FORCE, true)
            .setting(Channel.AUTO_JOIN, true)
            .setting(Channel.CONSOLE, true)
            .build()
    ));
```

And this is the section from the config that should be parsed.

```yaml
channels:
  # The id of the channel must be unique across your server network.
  # Channels with the same id on different servers in the same network are considered the same.
  # The id is used in commands and permissions.
  global:
    # The display name of the channel visible in the channel tabs and messages.
    # You can reference the name in the channel format via the <channel_name> tag.
    # It is also accessible via the PlaceholderAPI under {schat.channel_name} tag.
    # default: <channel_id>
    name: Global
    # The scope of the channel defines what players receive the messages.
    # The following scopes exist:
    #   - global: the message is sent to all players on all servers
    #   - server: the message is sent to all players on the server of the sender
    #   - world:  the message is sent only to players in the defined list of worlds.
    #             Use the 'worlds' config option to define a list of worlds this channel sends messages to.
    #   - local:  the message is only sent to players inside the defined 'range' of the message sender.
    #             Use the 'range' config option to set the range of the message.
    scope: global
    # The worlds option is only applicable if the scope is set to 'world'.
    # worlds:
    # - world
    # - world_nether
    # The range option is only applicable of the scope is set to 'local'.
    # default: 100
    # range: 100
    # Set 'true' to require a permission to join the channel.
    # The permission is: 'schat.channel.<id>', e.g. 'schat.channel.global'
    # default: false
    protect: false
    # Set 'true' to prevent players from leaving the channel.
    # default: false
    force: true
    # Set 'true' to automatically let every player that has the permission join this channel.
    # This is useful for global channels that everyone should have.
    # default: false
    auto_join: true
    # Sends all chat messages in this channel to the console as well.
    # Set false to not send messages in this channel to the console.
    # default: true
    console: true
    # The formatting of the chat messages in this channel.
    # Use any of the defined format templates (see below) or create a custom format for the channel.
    format: channel
    # Configures the line above the channel names.
    footer:
      enabled: true
  trade:
    name: Trade
    auto_join: true
    footer:
      enabled: false
```

Also another problem seems to be that the Object serializer does not use any other serializers I registered. I have one for the `displayName` which is a `Component`. The pure serialization here works fine:

```java
    @Comment("Fine-tune the behaviour of the console chat in this section.")
    private Console console = new Console();

    /**
     * Configuration for the console.
     *
     * @since next
     */
    @Getter
    @Setter
    @Accessors(fluent = true)
    public static class Console extends OkaeriConfig {

        @Comment("The name players see when chatting from the console.")
        private Component name = text("Console", RED);
        @Comment({
            "The channel the console will send chat messages to.",
            "Is silently ignored if the channel does not exist."
        })
        private String defaultChannel = "global";
    }
```

This is the serializer for `Component`:

```java
final class MiniMessageComponentSerializer extends BidirectionalTransformer<String, Component> {

    private final MiniMessage parser = MiniMessage.miniMessage();

    @Override
    public GenericsPair<String, Component> getPair() {
        return new GenericsPair<>(GenericsDeclaration.of(String.class), GenericsDeclaration.of(Component.class));
    }

    @Override
    public Component leftToRight(final @NonNull String data, final @NonNull SerdesContext serdesContext) {
        return parser.deserialize(data);
    }

    @Override
    public String rightToLeft(final @NonNull Component data, final @NonNull SerdesContext serdesContext) {
        return parser.serialize(data);
    }
}
```

But in the `Channel` serializer the following error is thrown:

```
failed to initialize dev.svoxel.chat.config.PluginConfig [class eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer]
eu.okaeri.configs.exception.OkaeriException: failed to initialize dev.svoxel.chat.config.PluginConfig [class eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer]
	at app//eu.okaeri.configs.ConfigManager.create(ConfigManager.java:55)
	at app//dev.svoxel.chat.SChatPlugin.setupAndLoadConfig(SChatPlugin.java:89)
	at app//dev.svoxel.chat.SChatPlugin.onEnable(SChatPlugin.java:82)
	at app//org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at app//org.bukkit.plugin.java.JavaPluginUtils.setEnabled(JavaPluginUtils.java:25)
	at app//be.seeseemelk.mockbukkit.plugin.PluginManagerMock.enablePlugin(PluginManagerMock.java:506)
	at app//be.seeseemelk.mockbukkit.MockBukkit.load(MockBukkit.java:179)
	at app//be.seeseemelk.mockbukkit.MockBukkit.load(MockBukkit.java:163)
	at app//dev.svoxel.chat.BukkitTestBase.setup(BukkitTestBase.java:47)
	at java.base@16.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@16.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base@16.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@16.0.2/java.lang.reflect.Method.invoke(Method.java:567)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$21(ClassBasedTestDescriptor.java:491)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:171)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:168)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@16.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@16.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@16.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@16.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base@16.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@16.0.2/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: eu.okaeri.configs.exception.OkaeriException: failed to #setValue for channels
	at app//eu.okaeri.configs.OkaeriConfig.save(OkaeriConfig.java:298)
	at app//eu.okaeri.configs.OkaeriConfig.save(OkaeriConfig.java:249)
	at app//eu.okaeri.configs.OkaeriConfig.save(OkaeriConfig.java:263)
	at app//eu.okaeri.configs.OkaeriConfig.save(OkaeriConfig.java:235)
	at app//eu.okaeri.configs.OkaeriConfig.load(OkaeriConfig.java:366)
	at app//dev.svoxel.chat.SChatPlugin.lambda$setupAndLoadConfig$0(SChatPlugin.java:93)
	at app//eu.okaeri.configs.ConfigManager.create(ConfigManager.java:52)
	... 95 more
Caused by: eu.okaeri.configs.exception.OkaeriException: cannot simplify type class net.kyori.adventure.text.TextComponentImpl (null): 'TextComponentImpl{content="Global", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}' [class net.kyori.adventure.text.TextComponentImpl]
	at app//eu.okaeri.configs.configurer.Configurer.simplify(Configurer.java:132)
	at app//eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer.simplify(YamlBukkitConfigurer.java:58)
	at app//eu.okaeri.configs.serdes.SerializationData.add(SerializationData.java:33)
	at app//dev.svoxel.chat.config.serializer.ChannelSerializer.serialize(ChannelSerializer.java:53)
	at app//dev.svoxel.chat.config.serializer.ChannelSerializer.serialize(ChannelSerializer.java:36)
	at app//eu.okaeri.configs.configurer.Configurer.simplify(Configurer.java:136)
	at app//eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer.simplify(YamlBukkitConfigurer.java:58)
	at app//eu.okaeri.configs.configurer.Configurer.simplifyMap(Configurer.java:80)
	at app//eu.okaeri.configs.configurer.Configurer.simplify(Configurer.java:129)
	at app//eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer.simplify(YamlBukkitConfigurer.java:58)
	at app//eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer.setValue(YamlBukkitConfigurer.java:75)
	at app//eu.okaeri.configs.OkaeriConfig.save(OkaeriConfig.java:296)
	... 101 more
```
