### ISSUE TITLE
Give access to root object in serializer

### ISSUE THREAD

**Issue by P3ridot** [OkaeriPoland/okaeri-configs#38]
I'd like to access root object in serializer. I'll give an exmaple:

I have object... For eg. ComplexMessage that contains ChatMessage & ActionbarMessage . In normal serializer I would serialize it to something like that:
```yaml
message:
  chat: "Chat message"
  actionbar: "Actionbar message"
```
which is fine when I have 2 messages types used

But when I have only 1 message type (for eg. chat) I ends up with 
```yaml
message:
  chat: "Chat message"
```

but I wants it's to be simpler - and serialize it as String:
```yaml
message: "Chat message"
```
